# Generated by Django 4.0.5 on 2022-06-19 23:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 19, 23, 49, 26, 548162, tzinfo=utc), verbose_name='Fecha de publicación'),
        ),
    ]
